COMMENT = S* Floating Window taskBar
VERSION = 1.0_beta16.1
REVISION = 0
CATEGORIES = wayland
PKGNAME = sfwbar
HOMEPAGE = https://github.com/LBCrion/sfwbar
ARCHIVE = v1.0_beta16.1.tar.gz
LINK = https://github.com/LBCrion/sfwbar/archive/refs/tags/v1.0_beta16.1.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = sfwbar-1.0_beta16.1
BUILD_OPTION = --buildtype=plain

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
