COMMENT = unicode string library
VERSION = 2.0.2
REVISION = 0
CATEGORIES = libs
PKGNAME = libgrapheme
HOMEPAGE = https://libs.suckless.org/libgrapheme
ARCHIVE = libgrapheme-2.0.2.tar.gz
LINK = https://dl.suckless.org/libgrapheme/libgrapheme-2.0.2.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = libgrapheme-2.0.2
MAKEOPT = LDCONFIG= all

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
