COMMENT = Utility functions for the X resource manager
VERSION = 1.3
REVISION = 0
CATEGORIES = libs
PKGNAME = xcb_util_xrm
HOMEPAGE = https://github.com/Airblader/xcb-util-xrm
ARCHIVE = xcb-util-xrm-1.3.tar.gz
LINK = https://github.com/Airblader/xcb-util-xrm/releases/download/v1.3/xcb-util-xrm-1.3.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = xcb-util-xrm-1.3
BUILD_OPTION =
AUTO_CONF = (cd ${BUILDDIR} && ./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--libdir=/usr/lib \
	--build=x86_64-pc-linux-musl)
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
