COMMENT =
VERSION =
REVISION =
CATEGORIES =
PKGNAME =
HOMEPAGE =
ARCHIVE =
LINK =
SRCCD =
BUILD =
BUILDDIR =
BUILD_OPTION =
AUTO_CONF =
MKINST = yes
MAKEOPT =

prepare:

# custom-build:
#

post_build:

include /usr/share/mk/lfs.port.mk
