COMMENT = Building blocks for modern GNOME applications
VERSION = 1.8.2
REVISION = 0
CATEGORIES = libs
PKGNAME = libadwaita
HOMEPAGE = https://gitlab.gnome.org/GNOME/libadwaita
ARCHIVE = libadwaita-1.8.2.tar.xz
LINK = https://download.gnome.org/sources/libadwaita/1.8/libadwaita-1.8.2.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = libadwaita-1.8.2
BUILD_OPTION = -Dexamples=false -Dgtk_doc=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
