COMMENT = A simple library to load images of various formats as SDL surfaces
VERSION = 2.8.8
REVISION = 0
CATEGORIES = libs
PKGNAME = sdl2_image
HOMEPAGE = https://github.com/libsdl-org/SDL_image
ARCHIVE = release-2.8.8.tar.gz
LINK = https://github.com/libsdl-org/SDL_image/archive/refs/tags/release-2.8.8.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = SDL_image-release-2.8.8
BUILD_OPTION = -DSDL2IMAGE_TESTS=OFF -DCMAKE_BUILD_TYPE=None

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
