COMMENT = LZ4 is lossless compression algorithm with fast decoder @ multiple GB/s per core.
VERSION = 1.10.0
REVISION = 0
CATEGORIES = compressors
PKGNAME = lz4
HOMEPAGE = https://github.com/lz4/lz4
ARCHIVE = v1.10.0.tar.gz
LINK = https://github.com/lz4/lz4/archive/v1.10.0.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = lz4-1.10.0
MAKEOPT =
CFLAGS = -O2 -flto=auto
CPPFLAGS = -O2 -flto=auto
export CFLAGS CPPFLAGS

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
