COMMENT = A C library to handle the Public Suffix List.
VERSION = 0.21.5
REVISION = 0
CATEGORIES = libs
PKGNAME = libpsl
HOMEPAGE = https://github.com/rockdaboot/libpsl
ARCHIVE = libpsl-0.21.5.tar.gz
LINK = https://github.com/rockdaboot/libpsl/releases/download/0.21.5/libpsl-0.21.5.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = libpsl-0.21.5
BUILD_OPTION = -Druntime=libidn2 --default-library=both

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
