COMMENT = low-level configuration system
VERSION = 1.6
REVISION = 0
CATEGORIES = libs
PKGNAME = libgcab
HOMEPAGE = https://wiki.gnome.org/Projects/libgcab
ARCHIVE = gcab-1.6.tar.xz
LINK = https://download.gnome.org/sources/gcab/1.6/gcab-1.6.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = gcab-1.6
BUILD_OPTION = -Ddocs=false -Dtests=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
