COMMENT = Direct Rendering Manager runtime library
VERSION = 1.5.10
REVISION = 0
CATEGORIES = libs
PKGNAME = libepoxy
HOMEPAGE = https://github.com/anholt/libepoxy
ARCHIVE = 1.5.10.tar.gz
LINK = https://github.com/anholt/libepoxy/archive/refs/tags/1.5.10.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = libepoxy-1.5.10
BUILD_OPTION = -Ddocs=false \
	-Degl=yes \
	-Dglx=yes \
	-Dx11=true \
	-Dtests=false

prepare:

custom-build:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
