COMMENT = Tiling window manager based on binary space partitioning
VERSION = 0.9.12
REVISION = 0
CATEGORIES = x11-wm
PKGNAME = bspwm
HOMEPAGE = https://github.com/baskerville/bspwm
ARCHIVE = ${VERSION}.tar.gz
LINK = ${HOMEPAGE}/archive/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = bspwm-${VERSION}

prepare:

post_build:

include /usr/share/mk/lfs.port.mk
