COMMENT = An efficient low latency audio codec
VERSION = 1.1.3
REVISION = 0
CATEGORIES = libs
PKGNAME = liblc3
HOMEPAGE = https://github.com/google/liblc3
ARCHIVE = v1.1.3.tar.gz
LINK = https://github.com/google/liblc3/archive/refs/tags/v1.1.3.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = liblc3-1.1.3
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
