COMMENT = Machine-readable files for the SPIR-V Registry
VERSION = 1.4.328.1
REVISION = 0
CATEGORIES = libs
PKGNAME = spirv_headers
HOMEPAGE = https://github.com/KhronosGroup/SPIRV-Headers
ARCHIVE = vulkan-sdk-1.4.328.1.tar.gz
LINK = https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-1.4.328.1.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = SPIRV-Headers-vulkan-sdk-1.4.328.1
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
