COMMENT = Grabs images from Wayland compositors
VERSION = 1.5.0
REVISION = 0
CATEGORIES = wayland
PKGNAME = grim
HOMEPAGE = https://gitlab.freedesktop.org/emersion/grim
ARCHIVE = grim-v1.5.0.tar.gz
LINK = https://gitlab.freedesktop.org/emersion/grim/-/archive/v1.5.0/grim-v1.5.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = grim-v1.5.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
