COMMENT = Simulate X11 keyboard/mouse input events
VERSION = 4.20251130.1
REVISION = 0
CATEGORIES = xapps
PKGNAME = xdotool
HOMEPAGE = https://github.com/jordansissel/xdotool
ARCHIVE = v4.20251130.1.tar.gz
LINK = https://github.com/jordansissel/xdotool/archive/v4.20251130.1.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = xdotool-4.20251130.1
MAKEOPT = WITHOUT_RPATH_FIX=1 INSTALLMAN=/usr/share/man

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
