COMMENT = A Free Implementation of the Unicode Bidirectional Algorithm.
VERSION = 1.0.16
REVISION = 0
CATEGORIES = libs
PKGNAME = fribidi
HOMEPAGE = https://github.com/fribidi/fribidi/
ARCHIVE = fribidi-1.0.16.tar.xz
LINK = https://github.com/fribidi/fribidi/releases/download/v1.0.16/fribidi-1.0.16.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = fribidi-1.0.16
BUILD_OPTION = --buildtype=release

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
