COMMENT = Correct PEP517 package builder
VERSION = 1.4.0
REVISION = 0
CATEGORIES = python
PKGNAME = pybuild
HOMEPAGE = https://github.com/pypa/build
ARCHIVE = py3-build-1.4.0.tar.gz
LINK = https://github.com/pypa/build/archive/refs/tags/1.4.0/py3-build-1.4.0.tar.gz
SRCCD = archive
BUILD = custom
BUILDDIR = build-1.4.0

prepare:

custom-build:
	cd ${BUILDDIR} && python3 -m flit_core.wheel
	cd ${BUILDDIR} && python3 -m installer --destdir "$(PWD)/pkg" dist/*.whl

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
