COMMENT = Filtering proxy for D-Bus connections
VERSION = 0.1.6
REVISION = 0
CATEGORIES = tool
PKGNAME = xdg_dbus_proxy
HOMEPAGE = https://github.com/flatpak/xdg-dbus-proxy/
ARCHIVE = xdg-dbus-proxy-0.1.6.tar.xz
LINK = https://github.com/flatpak/xdg-dbus-proxy/releases/download/0.1.6/xdg-dbus-proxy-0.1.6.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = xdg-dbus-proxy-0.1.6
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
