COMMENT = Utility for performing actions on windows in X
VERSION = 0.5.7
REVISION = 0
CATEGORIES = xapps
PKGNAME = xdo
HOMEPAGE = https://github.com/baskerville/xdo
ARCHIVE = xdo-0.5.7.tar.gz
LINK = https://github.com/baskerville/xdo/archive/0.5.7/xdo-0.5.7.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = xdo-0.5.7
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
