COMMENT = ICE authority file utility.
VERSION = 1.0.10
REVISION = 0
CATEGORIES = xapps
PKGNAME = iceauth
HOMEPAGE = https://www.x.org
ARCHIVE = iceauth-1.0.10.tar.gz
LINK = https://www.x.org/releases/individual/app/iceauth-1.0.10.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = iceauth-1.0.10
AUTO_CONF = (cd ${BUILDDIR} && ./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--libdir=/usr/lib \
	--build=x86_64-pc-linux-musl)
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
