COMMENT = C library for parsing INI-style files
VERSION = 4.2.6
REVISION = 0
CATEGORIES = libs
PKGNAME = iniparser
HOMEPAGE = https://github.com/ndevilla/iniparser
ARCHIVE = v4.2.6.tar.gz
LINK = https://github.com/ndevilla/iniparser/archive/v4.2.6.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = iniparser-4.2.6
BUILD_OPTION = -DBUILD_SHARED_LIBS=ON \
	-DCMAKE_BUILD_TYPE=MinSizeRel \
	-DBUILD_TESTING=OFF

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
