COMMENT = Tree is a recursive directory listing command.
VERSION = 2.2.1
REVISION = 1
CATEGORIES = tool
PKGNAME = tree
HOMEPAGE = https://oldmanprogrammer.net/source.php?dir=projects/tree
ARCHIVE = unix-tree-2.2.1.tar.gz
LINK = https://gitlab.com/OldManProgrammer/unix-tree/-/archive/2.2.1/unix-tree-2.2.1.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = unix-tree-2.2.1
MAKEOPT = MANDIR="../package/usr/share/man"
override PREFIX="../package/usr"
override DESTDIR="../package/usr/bin"

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
