COMMENT = A launcher/menu program for wlroots based wayland compositors.
VERSION = 1.5.1
REVISION = 0
CATEGORIES = wayland
PKGNAME = wofi
HOMEPAGE = https://hg.sr.ht/~scoopta/wofi
ARCHIVE = v1.5.1.tar.gz
LINK = https://hg.sr.ht/~scoopta/wofi/archive/v1.5.1.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = wofi-v1.5.1
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
