COMMENT = Python3 bindings for the cairo graphics library
VERSION = 1.28.0
REVISION = 0
CATEGORIES = python
PKGNAME = pycairo
HOMEPAGE = http://cairographics.org/pycairo/
ARCHIVE = pycairo-1.28.0.tar.gz
LINK = https://github.com/pygobject/pycairo/releases/download/v1.28.0/pycairo-1.28.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = pycairo-1.28.0
BUILD_OPTION = --libexecdir=/usr/libexec \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--includedir=/usr/include \
	--datadir=/usr/share \
	--mandir=/usr/man \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--buildtype=release

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
