COMMENT = Utilities for manipulating desktop files.
VERSION = 0.28
REVISION = 0
CATEGORIES = tool
PKGNAME = desktop_file_utils
HOMEPAGE = https://www.freedesktop.org/wiki/Software/desktop-file-utils/
ARCHIVE = desktop-file-utils-0.28.tar.xz
LINK = https://www.freedesktop.org/software/desktop-file-utils/releases/desktop-file-utils-0.28.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = desktop-file-utils-0.28
BUILD_OPTION = --buildtype=release

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
