COMMENT = Image viewer for X11/Wayland
VERSION = 4.5.0
REVISION = 0
CATEGORIES = tool
PKGNAME = imv
HOMEPAGE = https://sr.ht/~exec64/imv
ARCHIVE = v4.5.0.tar.gz
LINK = https://git.sr.ht/~exec64/imv/archive/v4.5.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = imv-v4.5.0
BUILD_OPTION = -Dwindows=wayland \
	-Dtest=disabled \
	-Dunicode=grapheme

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
